"""Added unique constraint for external_id and removed underlyings relationship

Revision ID: 2da76454a60b
Revises: b8b02a22b8ce
Create Date: 2025-05-25 21:41:02.835124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2da76454a60b'
down_revision: Union[str, None] = 'b8b02a22b8ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_securities_external_id'), table_name='securities')
    op.create_index(op.f('ix_securities_external_id'), 'securities', ['external_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_securities_external_id'), table_name='securities')
    op.create_index(op.f('ix_securities_external_id'), 'securities', ['external_id'], unique=False)
    # ### end Alembic commands ###
