"""Added derivative tables

Revision ID: 2fe568ac80bd
Revises: bcc8e5927401
Create Date: 2025-05-19 08:41:21.512337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fe568ac80bd'
down_revision: Union[str, None] = 'bcc8e5927401'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('futures',
    sa.Column('security_id', sa.UUID(), nullable=False),
    sa.Column('underlying_id', sa.UUID(), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=False),
    sa.Column('contract_size', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('lot_size', sa.Integer(), nullable=False),
    sa.Column('settlement_type', sa.String(length=20), nullable=False),
    sa.Column('contract_month', sa.String(length=10), nullable=False),
    sa.Column('initial_margin', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('maintenance_margin', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('previous_contract_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['previous_contract_id'], ['futures.security_id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['underlying_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('security_id'),
    sa.UniqueConstraint('underlying_id', 'contract_month', 'expiration_date', name='uq_future_contract')
    )
    op.create_index('idx_future_underlying', 'futures', ['underlying_id'], unique=False)
    op.create_index('idx_futures_expiration', 'futures', ['expiration_date'], unique=False)
    op.add_column('securities', sa.Column('segment', sa.String(length=20), nullable=False))
    op.add_column('securities', sa.Column('external_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_securities_external_id'), 'securities', ['external_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_securities_external_id'), table_name='securities')
    op.drop_column('securities', 'external_id')
    op.drop_column('securities', 'segment')
    op.drop_index('idx_futures_expiration', table_name='futures')
    op.drop_index('idx_future_underlying', table_name='futures')
    op.drop_table('futures')
    # ### end Alembic commands ###
