"""Initial DB Schema

Revision ID: 6ae7fb42c435
Revises: 
Create Date: 2025-06-06 21:32:30.967724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6ae7fb42c435'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchanges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exchanges_code'), 'exchanges', ['code'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('ml_models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('algorithm', sa.String(length=50), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hyperparameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('initial_capital', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('current_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('securities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('exchange_id', sa.UUID(), nullable=False),
    sa.Column('security_type', sa.String(length=20), nullable=False),
    sa.Column('segment', sa.String(length=20), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchanges.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'exchange_id', name='uq_symbol_exchange')
    )
    op.create_index(op.f('ix_securities_external_id'), 'securities', ['external_id'], unique=True)
    op.create_index(op.f('ix_securities_symbol'), 'securities', ['symbol'], unique=False)
    op.create_table('strategies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('backtest_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_continuity',
    sa.Column('security_id', sa.UUID(), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('first_data_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_next', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_records', sa.Integer(), nullable=False),
    sa.Column('gap_count', sa.Integer(), nullable=False),
    sa.Column('largest_gap_days', sa.Integer(), nullable=False),
    sa.Column('last_gap_check', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_quality_score', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('last_success', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_fill_enabled', sa.Boolean(), nullable=False),
    sa.Column('priority_level', sa.Integer(), nullable=False),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('consecutive_failures >= 0', name='check_failures_positive'),
    sa.CheckConstraint('data_quality_score >= 0.0 AND data_quality_score <= 1.0', name='check_continuity_quality_range'),
    sa.CheckConstraint('gap_count >= 0', name='check_gap_count_positive'),
    sa.CheckConstraint('largest_gap_days >= 0', name='check_largest_gap_positive'),
    sa.CheckConstraint('priority_level >= 1 AND priority_level <= 10', name='check_priority_range'),
    sa.CheckConstraint('total_records >= 0', name='check_total_records_positive'),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('security_id', 'timeframe')
    )
    op.create_index('idx_continuity_auto_fill', 'data_continuity', ['auto_fill_enabled'], unique=False)
    op.create_index('idx_continuity_expected_next', 'data_continuity', ['expected_next'], unique=False)
    op.create_index('idx_continuity_gap_count', 'data_continuity', ['gap_count'], unique=False)
    op.create_index('idx_continuity_last_update', 'data_continuity', ['last_update'], unique=False)
    op.create_index('idx_continuity_priority', 'data_continuity', ['priority_level'], unique=False)
    op.create_index('idx_continuity_quality', 'data_continuity', ['data_quality_score'], unique=False)
    op.create_table('data_quality_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('security_id', sa.UUID(), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('metric_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('overall_score', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('completeness_score', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('consistency_score', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('accuracy_score', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('timeliness_score', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('total_records', sa.Integer(), nullable=False),
    sa.Column('valid_records', sa.Integer(), nullable=False),
    sa.Column('invalid_records', sa.Integer(), nullable=False),
    sa.Column('duplicate_records', sa.Integer(), nullable=False),
    sa.Column('validation_rules_passed', sa.Integer(), nullable=False),
    sa.Column('validation_rules_failed', sa.Integer(), nullable=False),
    sa.Column('anomalies_detected', sa.Integer(), nullable=False),
    sa.Column('validation_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('accuracy_score >= 0.0 AND accuracy_score <= 1.0', name='check_accuracy_score_range'),
    sa.CheckConstraint('completeness_score >= 0.0 AND completeness_score <= 1.0', name='check_completeness_score_range'),
    sa.CheckConstraint('consistency_score >= 0.0 AND consistency_score <= 1.0', name='check_consistency_score_range'),
    sa.CheckConstraint('invalid_records >= 0', name='check_invalid_records_positive'),
    sa.CheckConstraint('overall_score >= 0.0 AND overall_score <= 1.0', name='check_overall_score_range'),
    sa.CheckConstraint('timeliness_score >= 0.0 AND timeliness_score <= 1.0', name='check_timeliness_score_range'),
    sa.CheckConstraint('total_records >= 0', name='check_total_records_positive'),
    sa.CheckConstraint('valid_records + invalid_records <= total_records', name='check_record_counts_consistent'),
    sa.CheckConstraint('valid_records >= 0', name='check_valid_records_positive'),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_quality_date_timeframe', 'data_quality_metrics', ['metric_date', 'timeframe'], unique=False)
    op.create_index('idx_quality_overall_score', 'data_quality_metrics', ['overall_score'], unique=False)
    op.create_index('idx_quality_security_date', 'data_quality_metrics', ['security_id', 'metric_date'], unique=False)
    op.create_index('idx_quality_source', 'data_quality_metrics', ['source'], unique=False)
    op.create_index(op.f('ix_data_quality_metrics_metric_date'), 'data_quality_metrics', ['metric_date'], unique=False)
    op.create_index(op.f('ix_data_quality_metrics_security_id'), 'data_quality_metrics', ['security_id'], unique=False)
    op.create_table('futures',
    sa.Column('security_id', sa.UUID(), nullable=False),
    sa.Column('underlying_id', sa.UUID(), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=False),
    sa.Column('contract_size', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('lot_size', sa.Integer(), nullable=False),
    sa.Column('settlement_type', sa.String(length=20), nullable=False),
    sa.Column('contract_month', sa.String(length=10), nullable=False),
    sa.Column('initial_margin', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('maintenance_margin', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('previous_contract_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['previous_contract_id'], ['futures.security_id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['underlying_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('security_id'),
    sa.UniqueConstraint('security_id', name='uq_future_security_id'),
    sa.UniqueConstraint('underlying_id', 'contract_month', 'expiration_date', 'settlement_type', name='uq_future_contract_details')
    )
    op.create_index('idx_future_active', 'futures', ['is_active'], unique=False)
    op.create_index('idx_future_contract_month', 'futures', ['contract_month'], unique=False)
    op.create_index('idx_future_underlying', 'futures', ['underlying_id'], unique=False)
    op.create_index('idx_futures_expiration', 'futures', ['expiration_date'], unique=False)
    op.create_table('ml_predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('security_id', sa.UUID(), nullable=False),
    sa.Column('prediction_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('target', sa.String(length=50), nullable=False),
    sa.Column('prediction_value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('features_used', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['ml_models.id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_predictions_prediction_time'), 'ml_predictions', ['prediction_time'], unique=False)
    op.create_table('ohlcv_unified',
    sa.Column('security_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('high', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('low', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('close', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('adjusted_close', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('quality_score', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("timeframe IN ('daily', 'weekly', 'monthly')", name='check_timeframe_valid'),
    sa.CheckConstraint('high >= GREATEST(open, close, low)', name='check_high_valid'),
    sa.CheckConstraint('low <= LEAST(open, close, high)', name='check_low_valid'),
    sa.CheckConstraint('open > 0 AND high > 0 AND low > 0 AND close > 0', name='check_prices_positive'),
    sa.CheckConstraint('quality_score >= 0.0 AND quality_score <= 1.0', name='check_quality_score_range'),
    sa.CheckConstraint('volume >= 0', name='check_volume_positive'),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('security_id', 'timestamp', 'timeframe')
    )
    op.create_index('idx_ohlcv_created_at', 'ohlcv_unified', ['created_at'], unique=False)
    op.create_index('idx_ohlcv_daily_recent', 'ohlcv_unified', ['security_id', 'timestamp'], unique=False, postgresql_where=sa.text("timeframe = 'daily'"))
    op.create_index('idx_ohlcv_quality', 'ohlcv_unified', ['quality_score'], unique=False)
    op.create_index('idx_ohlcv_security_timeframe', 'ohlcv_unified', ['security_id', 'timeframe'], unique=False)
    op.create_index('idx_ohlcv_security_timestamp', 'ohlcv_unified', ['security_id', 'timestamp'], unique=False)
    op.create_index('idx_ohlcv_source', 'ohlcv_unified', ['source'], unique=False)
    op.create_index('idx_ohlcv_timestamp_timeframe', 'ohlcv_unified', ['timestamp', 'timeframe'], unique=False)
    op.create_index('idx_ohlcv_weekly_recent', 'ohlcv_unified', ['security_id', 'timestamp'], unique=False, postgresql_where=sa.text("timeframe = 'weekly'"))
    op.create_index(op.f('ix_ohlcv_unified_security_id'), 'ohlcv_unified', ['security_id'], unique=False)
    op.create_index(op.f('ix_ohlcv_unified_timeframe'), 'ohlcv_unified', ['timeframe'], unique=False)
    op.create_index(op.f('ix_ohlcv_unified_timestamp'), 'ohlcv_unified', ['timestamp'], unique=False)
    op.create_table('pipeline_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('security_id', sa.UUID(), nullable=True),
    sa.Column('securities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('date_range', postgresql.TSTZRANGE(), nullable=True),
    sa.Column('timeframe', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_category', sa.String(length=50), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dependencies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("job_type IN ('ingest', 'aggregate', 'gap_fill', 'validate', 'cleanup')", name='check_job_type_valid'),
    sa.CheckConstraint("status IN ('pending', 'running', 'completed', 'failed', 'cancelled')", name='check_status_valid'),
    sa.CheckConstraint('max_retries >= 0', name='check_max_retries_positive'),
    sa.CheckConstraint('priority >= 1 AND priority <= 10', name='check_job_priority_range'),
    sa.CheckConstraint('progress >= 0 AND progress <= 100', name='check_progress_range'),
    sa.CheckConstraint('retry_count >= 0', name='check_retry_count_positive'),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_jobs_active', 'pipeline_jobs', ['status', 'priority', 'created_at'], unique=False, postgresql_where=sa.text("status IN ('pending', 'running')"))
    op.create_index('idx_jobs_created_at', 'pipeline_jobs', ['created_at'], unique=False)
    op.create_index('idx_jobs_failed_retryable', 'pipeline_jobs', ['job_type', 'retry_count', 'created_at'], unique=False, postgresql_where=sa.text("status = 'failed' AND retry_count < max_retries"))
    op.create_index('idx_jobs_heartbeat', 'pipeline_jobs', ['last_heartbeat'], unique=False)
    op.create_index('idx_jobs_security_status', 'pipeline_jobs', ['security_id', 'status'], unique=False)
    op.create_index('idx_jobs_started_at', 'pipeline_jobs', ['started_at'], unique=False)
    op.create_index('idx_jobs_status_priority', 'pipeline_jobs', ['status', 'priority'], unique=False)
    op.create_index('idx_jobs_type_status', 'pipeline_jobs', ['job_type', 'status'], unique=False)
    op.create_index(op.f('ix_pipeline_jobs_job_type'), 'pipeline_jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_pipeline_jobs_security_id'), 'pipeline_jobs', ['security_id'], unique=False)
    op.create_index(op.f('ix_pipeline_jobs_status'), 'pipeline_jobs', ['status'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('security_id', sa.UUID(), nullable=False),
    sa.Column('signal_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('generation_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('signal_type', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('parameters_used', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_signal_time'), 'signals', ['signal_time'], unique=False)
    op.create_table('strategy_securities',
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('security_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('strategy_id', 'security_id')
    )
    op.create_table('backtest_results',
    sa.Column('backtest_id', sa.UUID(), nullable=False),
    sa.Column('total_return', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('annualized_return', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('sharpe_ratio', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('sortino_ratio', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('max_drawdown', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('win_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('profit_factor', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('equity_curve', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['backtest_id'], ['backtest_runs.id'], ),
    sa.PrimaryKeyConstraint('backtest_id')
    )
    op.create_table('backtest_trades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('backtest_id', sa.UUID(), nullable=False),
    sa.Column('security_id', sa.UUID(), nullable=False),
    sa.Column('entry_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('exit_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('profit_loss', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('profit_loss_pct', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('exit_reason', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['backtest_id'], ['backtest_runs.id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_trades_backtest_id'), 'backtest_trades', ['backtest_id'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('security_id', sa.UUID(), nullable=False),
    sa.Column('signal_id', sa.UUID(), nullable=True),
    sa.Column('entry_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('exit_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('profit_loss', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('profit_loss_pct', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('positions')
    op.drop_index(op.f('ix_backtest_trades_backtest_id'), table_name='backtest_trades')
    op.drop_table('backtest_trades')
    op.drop_table('backtest_results')
    op.drop_table('strategy_securities')
    op.drop_index(op.f('ix_signals_signal_time'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_pipeline_jobs_status'), table_name='pipeline_jobs')
    op.drop_index(op.f('ix_pipeline_jobs_security_id'), table_name='pipeline_jobs')
    op.drop_index(op.f('ix_pipeline_jobs_job_type'), table_name='pipeline_jobs')
    op.drop_index('idx_jobs_type_status', table_name='pipeline_jobs')
    op.drop_index('idx_jobs_status_priority', table_name='pipeline_jobs')
    op.drop_index('idx_jobs_started_at', table_name='pipeline_jobs')
    op.drop_index('idx_jobs_security_status', table_name='pipeline_jobs')
    op.drop_index('idx_jobs_heartbeat', table_name='pipeline_jobs')
    op.drop_index('idx_jobs_failed_retryable', table_name='pipeline_jobs', postgresql_where=sa.text("status = 'failed' AND retry_count < max_retries"))
    op.drop_index('idx_jobs_created_at', table_name='pipeline_jobs')
    op.drop_index('idx_jobs_active', table_name='pipeline_jobs', postgresql_where=sa.text("status IN ('pending', 'running')"))
    op.drop_table('pipeline_jobs')
    op.drop_index(op.f('ix_ohlcv_unified_timestamp'), table_name='ohlcv_unified')
    op.drop_index(op.f('ix_ohlcv_unified_timeframe'), table_name='ohlcv_unified')
    op.drop_index(op.f('ix_ohlcv_unified_security_id'), table_name='ohlcv_unified')
    op.drop_index('idx_ohlcv_weekly_recent', table_name='ohlcv_unified', postgresql_where=sa.text("timeframe = 'weekly'"))
    op.drop_index('idx_ohlcv_timestamp_timeframe', table_name='ohlcv_unified')
    op.drop_index('idx_ohlcv_source', table_name='ohlcv_unified')
    op.drop_index('idx_ohlcv_security_timestamp', table_name='ohlcv_unified')
    op.drop_index('idx_ohlcv_security_timeframe', table_name='ohlcv_unified')
    op.drop_index('idx_ohlcv_quality', table_name='ohlcv_unified')
    op.drop_index('idx_ohlcv_daily_recent', table_name='ohlcv_unified', postgresql_where=sa.text("timeframe = 'daily'"))
    op.drop_index('idx_ohlcv_created_at', table_name='ohlcv_unified')
    op.drop_table('ohlcv_unified')
    op.drop_index(op.f('ix_ml_predictions_prediction_time'), table_name='ml_predictions')
    op.drop_table('ml_predictions')
    op.drop_index('idx_futures_expiration', table_name='futures')
    op.drop_index('idx_future_underlying', table_name='futures')
    op.drop_index('idx_future_contract_month', table_name='futures')
    op.drop_index('idx_future_active', table_name='futures')
    op.drop_table('futures')
    op.drop_index(op.f('ix_data_quality_metrics_security_id'), table_name='data_quality_metrics')
    op.drop_index(op.f('ix_data_quality_metrics_metric_date'), table_name='data_quality_metrics')
    op.drop_index('idx_quality_source', table_name='data_quality_metrics')
    op.drop_index('idx_quality_security_date', table_name='data_quality_metrics')
    op.drop_index('idx_quality_overall_score', table_name='data_quality_metrics')
    op.drop_index('idx_quality_date_timeframe', table_name='data_quality_metrics')
    op.drop_table('data_quality_metrics')
    op.drop_index('idx_continuity_quality', table_name='data_continuity')
    op.drop_index('idx_continuity_priority', table_name='data_continuity')
    op.drop_index('idx_continuity_last_update', table_name='data_continuity')
    op.drop_index('idx_continuity_gap_count', table_name='data_continuity')
    op.drop_index('idx_continuity_expected_next', table_name='data_continuity')
    op.drop_index('idx_continuity_auto_fill', table_name='data_continuity')
    op.drop_table('data_continuity')
    op.drop_table('backtest_runs')
    op.drop_table('strategies')
    op.drop_index(op.f('ix_securities_symbol'), table_name='securities')
    op.drop_index(op.f('ix_securities_external_id'), table_name='securities')
    op.drop_table('securities')
    op.drop_table('portfolios')
    op.drop_table('ml_models')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_exchanges_code'), table_name='exchanges')
    op.drop_table('exchanges')
    # ### end Alembic commands ###
