"""Added OHLCV Progress Table

Revision ID: b8b02a22b8ce
Revises: c797b8ad6b63
Create Date: 2025-05-24 21:03:11.575759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8b02a22b8ce'
down_revision: Union[str, None] = 'c797b8ad6b63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ohlcv_fetch_progress',
    sa.Column('security_id', sa.UUID(), nullable=False),
    sa.Column('last_historical_fetch', sa.Date(), nullable=True),
    sa.Column('last_daily_fetch', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('security_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ohlcv_fetch_progress')
    # ### end Alembic commands ###
