"""Derivative table relationship fixed

Revision ID: c797b8ad6b63
Revises: ee9070b4c569
Create Date: 2025-05-24 18:00:09.557450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c797b8ad6b63'
down_revision: Union[str, None] = 'ee9070b4c569'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_future_contract'), 'futures', type_='unique')
    op.create_index('idx_future_active', 'futures', ['is_active'], unique=False)
    op.create_index('idx_future_contract_month', 'futures', ['contract_month'], unique=False)
    op.create_unique_constraint('uq_future_contract_details', 'futures', ['underlying_id', 'contract_month', 'expiration_date', 'settlement_type'])
    op.create_unique_constraint('uq_future_security_id', 'futures', ['security_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_future_security_id', 'futures', type_='unique')
    op.drop_constraint('uq_future_contract_details', 'futures', type_='unique')
    op.drop_index('idx_future_contract_month', table_name='futures')
    op.drop_index('idx_future_active', table_name='futures')
    op.create_unique_constraint(op.f('uq_future_contract'), 'futures', ['underlying_id', 'contract_month', 'expiration_date'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
